# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure your secret_key_base is kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 'd132fd22bc612e157d722e980c4b0525b938f225f9f7f66ea2638adb7e865299f897109a7877991824473b40e0fc3b539aa8bbe252e1995ad025bf6031b78311'
  service_login: scalarm
  service_password: scalarm

test:
  secret_key_base: 'd132fd22bc612e157d722e980c4b0525b938f225f9f7f66ea2638adb7e865299f897109a7877991824473b40e0fc3b539aa8bbe252e1995ad025bf6031b78311'
  service_login: scalarm
  service_password: scalarm

production:
  # it should be
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # TODO FIXME - remember to have different values on production
  secret_key_base: 'd132fd22bc612e157d722e980c4b0525b938f225f9f7f66ea2638adb7e865299f897109a7877991824473b40e0fc3b539aa8bbe252e1995ad025bf6031b78311'

  service_login: scalarm
  service_password: scalarm

  service_crt: ./config/scalarm-cert.pem
  service_key: ./config/scalarm-cert-key.pem



